### ISSUE TITLE
Linux shared library dependencies

### ISSUE THREAD

**Issue by joneshf** [purescript-contrib/node-purescript-bin#2]
The linux version of psci requires `libtinfo` among other things, so this information should be included somewhere, maybe in the readme. Or it could be checked before installation and it halted if not found, then direct the user to install the appropriate things.

```
➜  ~  _ npm i -g purescript 
/usr/bin/psc -> /usr/lib/node_modules/purescript/bin/psc.js
/usr/bin/psc-docs -> /usr/lib/node_modules/purescript/bin/psc-docs.js
/usr/bin/psc-make -> /usr/lib/node_modules/purescript/bin/psc-make.js
/usr/bin/psci -> /usr/lib/node_modules/purescript/bin/psci.js

> purescript@0.6.9 postinstall /usr/lib/node_modules/purescript
> node lib/install.js

  ✔ psc pre-build test passed successfully
  ✔ psc-docs pre-build test passed successfully
  ✔ psc-make pre-build test passed successfully
  ⚠ The `/usr/lib/node_modules/purescript/vendor/psci` binary doesn't seem to work correctly
  ⚠ psci pre-build test failed
  ℹ compiling from source
  ✖ Error: cabal update && cabal install --bindir /usr/lib/node_modules/purescript/vendor
Command failed: /bin/sh -c cabal update
cabal: /root/.cabal/config: permission denied

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
purescript@0.6.9 /usr/lib/node_modules/purescript
├── async-each-series@0.1.1
├── logalot@2.1.0 (figures@1.3.5, squeak@1.2.0)
├── bin-wrapper@3.0.0 (os-filter-obj@1.0.3, bin-version-check@2.1.0, bin-check@1.0.0, globby@1.2.0, download@4.1.2)
└── bin-build@2.1.1 (exec-series@1.0.1, url-regex@2.1.2, tempfile@1.1.0, archive-type@2.0.0, rimraf@2.3.2, decompress@2.2.1, download@3.3.0)
➜  ~  psci
/usr/lib/node_modules/purescript/vendor/psci: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

here's an `ldd`:

```
➜  ~  ldd /usr/lib/node_modules/purescript/vendor/psci
	linux-vdso.so.1 (0x00007ffdb4796000)
	libtinfo.so.5 => not found
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f1991d6f000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f1991b6b000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007f19918d9000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f19915d4000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f19913be000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f199101b000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f1990dfe000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1991f77000)
```

N.B. This isn't a problem when building psci from the repo itself. But the fallback of building cabal locally might fail due to normal cabal issues, or not having it installed in the first place. I get this when attempting to install locally (even with a sandbox in the same directory):

```
➜  baz  npm i purescript  
npm WARN package.json baz@1.0.0 No description
npm WARN package.json baz@1.0.0 No repository field.
npm WARN package.json baz@1.0.0 No README data
-
> purescript@0.6.9 postinstall /home/joneshf/foo/bar/baz/node_modules/purescript
> node lib/install.js

  ✔ psc pre-build test passed successfully
  ✔ psc-docs pre-build test passed successfully
  ✔ psc-make pre-build test passed successfully
  ⚠ The `/home/joneshf/foo/bar/baz/node_modules/purescript/vendor/psci` binary doesn't seem to work correctly
  ⚠ psci pre-build test failed
  ℹ compiling from source
  ✖ Error: cabal update && cabal install --bindir /home/joneshf/foo/bar/baz/node_modules/purescript/vendor
Command failed: /bin/sh -c cabal install --bindir /home/joneshf/foo/bar/baz/node_modules/purescript/vendor
cabal: The following packages are likely to be broken by the reinstalls:
network-uri-2.6.0.1
HTTP-4000.2.19
Use --force-reinstalls if you want to install anyway.

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
purescript@0.6.9 node_modules/purescript
├── async-each-series@0.1.1
├── logalot@2.1.0 (figures@1.3.5, squeak@1.2.0)
├── bin-build@2.1.1 (exec-series@1.0.1, url-regex@2.1.2, tempfile@1.1.0, archive-type@2.0.0, rimraf@2.3.2, decompress@2.2.1, download@3.3.0)
└── bin-wrapper@3.0.0 (os-filter-obj@1.0.3, bin-check@1.0.0, bin-version-check@2.1.0, globby@1.2.0, download@4.1.2)

```

**Comment by shinnn** [comment]
@joneshf Thanks for reporting.

I'll update the doc first. Where can I read the information of the dependencies? I want to add its URL to the readme.

**Comment by joneshf** [comment]
I'm not sure where to find an explicit list of shared library deps. I think it has to do with what is used during compilation, as the other binaries have slightly different deps.

**Comment by shinnn** [comment]
> I'm not sure where to find an explicit list of shared library deps.

First of all they should be documented on [the website](http://www.purescript.org/), [the wiki](https://github.com/purescript/purescript/wiki) or anywhere else.

// @purescript-contrib/owners

**Comment by hdgarrood** [comment]
I'm pretty sure it's just `libtinfo`. See [INSTALL.md](https://github.com/purescript/purescript/blob/896bbcdb91c43b3054297e8c3a28592f00de07d3/INSTALL.md) for this information.

**Comment by shinnn** [comment]
Fixed in https://github.com/purescript-contrib/node-purescript-bin/commit/756c53d995dc0844c0ff3d972c7b8b1bc505f7e6. Thnaks for the advice, @hdgarrood!

**Comment by hdgarrood** [comment]
No problem :)
