### ISSUE TITLE
http://www.purescript.org/learn/getting-started/ should mention dependency on stack

### ISSUE THREAD

**Issue by roman-neuhauser** [purescript-contrib/node-purescript-bin#32]
originally reported in https://github.com/purescript/purescript/issues/2463, got sent here.

--

http://www.purescript.org/learn/getting-started/ assumes i have stack already installed:

```
roman@sheeba ~ master :M 0 1017 0 . su -l root           
Password:
root@sheeba:~ # npm install -g purescript
/usr/local/bin/psc -> /usr/local/lib/node_modules/purescript/bin/psc.js
/usr/local/bin/psc-bundle -> /usr/local/lib/node_modules/purescript/bin/psc-bundle.js
/usr/local/bin/psc-docs -> /usr/local/lib/node_modules/purescript/bin/psc-docs.js
/usr/local/bin/psc-ide-client -> /usr/local/lib/node_modules/purescript/bin/psc-ide-client.js
/usr/local/bin/psc-ide-server -> /usr/local/lib/node_modules/purescript/bin/psc-ide-server.js
/usr/local/bin/psc-package -> /usr/local/lib/node_modules/purescript/bin/psc-package.js
/usr/local/bin/psci -> /usr/local/lib/node_modules/purescript/bin/psci.js
/usr/local/bin/psc-publish -> /usr/local/lib/node_modules/purescript/bin/psc-publish.js

> purescript@0.10.2 postinstall /usr/local/lib/node_modules/purescript
> node lib/install.js

  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
/bin/sh: stack: not found

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc-bundle pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
/bin/sh: stack: not found

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc-docs pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
/bin/sh: stack: not found

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc-ide-client pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
/bin/sh: stack: not found

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc-ide-server pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
/bin/sh: stack: not found

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc-package pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
/bin/sh: stack: not found

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc-publish pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
/bin/sh: stack: not found

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psci pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
/bin/sh: stack: not found

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
/usr/local/lib
`-- purescript@0.10.2 

root@sheeba:~ # logout
roman@sheeba ~ master :M 0 1018 0 . rehash
roman@sheeba ~ master :M 0 1019 0 . pulp psci
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/lib/node_modules/purescript/vendor/psc ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
* ERROR: Subcommand terminated with exit code 1
roman@sheeba ~ master :M 0 1020 1 . 
```

**Comment by shinnn** [comment]
Not a node-purescript-bin issue.

**Comment by garyb** [comment]
Probably worth mentioning the fallback-to-stack behaviour in the README here though?

**Comment by hdgarrood** [comment]
I think the UI could be improved quite significantly in node-purescript-bin by checking whether `stack` exists before attempting to build binaries from source, and if not, exiting immediately with a more helpful message (including a link to https://docs.haskellstack.org/en/stable/README/).
