### ISSUE TITLE
npm install -g purescript fails on FreeBSD

### ISSUE THREAD

**Issue by roman-neuhauser** [purescript-contrib/node-purescript-bin#33]
originally reported in https://github.com/purescript/purescript/issues/2463, got sent here.

```
roman@sheeba ~ master :M 0 1019 0 . sudo pkg install stack
Updating FreeBSD repository catalogue...
Fetching meta.txz: 100%    944 B   0.9kB/s    00:01    
Fetching packagesite.txz: 100%    6 MiB 387.4kB/s    00:15    
Processing entries: 100%
FreeBSD repository update completed. 25606 packages processed.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	stack: 1.2.0

Number of packages to be installed: 1

The process will require 42 MiB more space.
6 MiB to be downloaded.

Proceed with this action? [y/N]: y
Fetching stack-1.2.0.txz: 100%    6 MiB 302.6kB/s    00:20    
Checking integrity... done (0 conflicting)
[1/1] Installing stack-1.2.0...
[1/1] Extracting stack-1.2.0: 100%
```

```
roman@sheeba ~ master :M 0 1020 0 . su -l
Password:
root@sheeba:~ # npm install -g purescript
/usr/local/bin/psc -> /usr/local/lib/node_modules/purescript/bin/psc.js
/usr/local/bin/psc-bundle -> /usr/local/lib/node_modules/purescript/bin/psc-bundle.js
/usr/local/bin/psc-ide-client -> /usr/local/lib/node_modules/purescript/bin/psc-ide-client.js
/usr/local/bin/psc-package -> /usr/local/lib/node_modules/purescript/bin/psc-package.js
/usr/local/bin/psc-ide-server -> /usr/local/lib/node_modules/purescript/bin/psc-ide-server.js
/usr/local/bin/psc-docs -> /usr/local/lib/node_modules/purescript/bin/psc-docs.js
/usr/local/bin/psc-publish -> /usr/local/lib/node_modules/purescript/bin/psc-publish.js
/usr/local/bin/psci -> /usr/local/lib/node_modules/purescript/bin/psci.js

> purescript@0.10.2 postinstall /usr/local/lib/node_modules/purescript
> node lib/install.js

  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
Preventing creation of stack root '/root/.stack/'. Parent directory '/root/' is owned by someone else.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc-bundle pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
Preventing creation of stack root '/root/.stack/'. Parent directory '/root/' is owned by someone else.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc-docs pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
Preventing creation of stack root '/root/.stack/'. Parent directory '/root/' is owned by someone else.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc-ide-client pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
Preventing creation of stack root '/root/.stack/'. Parent directory '/root/' is owned by someone else.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc-ide-server pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
Preventing creation of stack root '/root/.stack/'. Parent directory '/root/' is owned by someone else.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc-package pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
Preventing creation of stack root '/root/.stack/'. Parent directory '/root/' is owned by someone else.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc-publish pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
Preventing creation of stack root '/root/.stack/'. Parent directory '/root/' is owned by someone else.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psci pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
Preventing creation of stack root '/root/.stack/'. Parent directory '/root/' is owned by someone else.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
/usr/local/lib
`-- purescript@0.10.2 

root@sheeba:~ # ls -ld /root/ /root/.stack /root/.stack/
ls: /root/.stack: No such file or directory
ls: /root/.stack/: No such file or directory
drwxr-xr-x  4 root  wheel  12 Dec  5 09:44 /root/
```

i have no idea how to interpret the error messages.

**Comment by shinnn** [comment]
Not a node-purescript-bin issue.
