### ISSUE TITLE
installation fails on FreeBSD

### ISSUE THREAD

**Issue by j-keck** [purescript-contrib/node-purescript-bin#49]
For FreeBSD are no prebuild binaries available. 

The installation script use `stack` with the `--local-bin-path` parameter to compile it from source. 
`stack` does not create the directory if it does not exist and the build fails.

```
~ ⟩ npm -g install purescript                                                                                                                                                                ~
/home/j/.npm-packages/bin/purs -> /home/j/.npm-packages/lib/node_modules/purescript/bin/purs.js

> purescript@0.11.5 postinstall /home/j/.npm-packages/lib/node_modules/purescript
> node lib/install.js

  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup --allow-different-user && stack install --allow-different-user --local-bin-path /usr/home/j/.npm-packages/lib/node_modules/purescript/vendor
Command failed: stack install --allow-different-user --local-bin-path /usr/home/j/.npm-packages/lib/node_modules/purescript/vendor
No directory could be located matching the supplied path: /usr/home/j/.npm-packages/lib/node_modules/purescript/vendor

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
/home/j/.npm-packages/lib
└── purescript@0.11.5 
```

**Comment by shinnn** [comment]
By removing [these lines](https://github.com/purescript-contrib/node-purescript-bin/blob/2b05d8d0e71da1c4c7ed24ce54b96a5364c2cb87/lib/install.js#L13-L15), we can simulate the environment where the prebuilt binary is not provided.

On my macOS, I used this trick and ran `npm install`, then `node-purescript-bin` started to build `purs` binary from source.

Surprisingly, unlike the @j-keck's report, it automatically created the `vendor` directory and the build succeeded.

```
$ stack --numeric-version
1.4.0

$ ls ./vendor
ls: ./vendor: No such file or directory

$ npm i

> purescript@0.11.5 postinstall /Users/Shinnosuke/github/node-purescript-bin
> node lib/install.js

  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ pre-build test failed
  ℹ compiling from source

$ ls ./vendor
purs
```

1. @j-keck What's your `stack --version` ?
2. Is the "No directory could be located" error is FreeBSD specific? I should dig in [the source code of Haskell Stack](https://github.com/commercialhaskell/stack).

**Comment by j-keck** [comment]
@shinnn : i'm also on stack 1.4.0:

```
~ ⟩ stack --numeric-version                                                             ~
1.4.0
                                                                                                                                                              
~ ⟩ cd .npm-packages/lib/node_modules/purescript                     ~

 ..modules/purescript ⟩ npm i                                                           ~/.npm-packages/lib/node_module/purescript

> purescript@0.11.5 postinstall /usr/home/j/.npm-packages/lib/node_modules/purescript
> node lib/install.js

  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup --allow-different-user && stack install --allow-different-user --local-bin-path /usr/home/j/.npm-packages/lib/node_modules/purescript/vendor
Command failed: stack install --allow-different-user --local-bin-path /usr/home/j/.npm-packages/lib/node_modules/purescript/vendor
No directory could be located matching the supplied path: /usr/home/j/.npm-packages/lib/node_modules/purescript/vendor

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
purescript@0.11.5 /usr/home/j/.npm-packages/lib/node_modules/purescript
├─┬ @shinnn/eslint-config-node@3.0.0 
│ └── @shinnn/eslint-config@3.4.0 
├─┬ eslint@3.19.0 
│ ├─┬ babel-code-frame@6.22.0 
│ │ ├── esutils@2.0.2  deduped
....
```

**Comment by j-keck** [comment]
@shinnn was a problem on my side:

`stack` calls `Path.IO.resolveDir'` which calls `System.Directory.canonicalizePath` in:
https://github.com/commercialhaskell/stack/blob/ea10057da1b1a49d937e7bcb6f997360bec1f863/src/Stack/Config.hs#L354-L369

i was on `lts-6.24` (defined in  ~/.stack/global/stack.yaml). after bump to `lts.8.17` the problem disappear.

it was a problem with `System.Directory.canonicalizePath`:
```
~ ⟩ stack ghci --package path-io --resolver=lts-6.24 
Configuring GHCi with the following packages: 
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
λ: :m +System.Directory
λ: canonicalizePath "/abc/def"
*** Exception: /abc/def: canonicalizePath: does not exist (No such file or directory)
λ: 
Leaving GHCi.
```
```
~ ⟩ stack ghci --package path-io --resolver=lts-8.17
Configuring GHCi with the following packages: 
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help

λ: :m +System.Directory
λ: canonicalizePath "/abc/def"
"/abc/def"
```
sorry for the noise!

**Comment by shinnn** [comment]
@j-keck No problem. Thanks for the clarification!
